### ISSUE TITLE
An option to explicitly type shims as `any`

### ISSUE THREAD

**Issue by sgwilym** [denoland/dnt#107]
I always seem to have a bit of trouble finding polyfills which tick all the boxes whenever I want to shim something with `shims.custom`.

Example: 
- I'm using `structuredClone`
- There's a polyfill at https://github.com/ungap/structured-clone
- But it doesn't have type declarations, so errors are raised during the type-checking phase (`Could not find a declaration file for module '@ungap/structured-clone'`)

I would love there to be a way to type a shim as `any` from the config, as you'd assume a polyfill would be of the same type as the thing it's shimming for.

**Comment by dsherret** [comment]
It should be possible to do this now by creating a local javascript shim and re-exporting anything necessary from the node package. I believe it should work, but let me know if you run into any trouble.
