### ISSUE TITLE
Describe usage with watch

### ISSUE THREAD

**Issue by steida** [denoland/dnt#112]
Not sure how to rebuild on file change. Thank you.

**Comment by steida** [comment]
A workaround, for now, is `import * as foo from "../mod.ts";` to `build_npm.ts`

Then: `deno run -A --watch scripts/build_npm.ts`

**Comment by ah-yu** [comment]
@steida You could pass file paths that you want to watch as arguments to `watch` flag.

`deno run -A --watch=src scripts/build_npm.ts`

**Comment by steida** [comment]
Thank you.
