### ISSUE TITLE
UMD build does not work with Webpack

### ISSUE THREAD

**Issue by daffl** [denoland/dnt#113]
We recently moved the development of https://github.com/feathersjs/hooks to Deno first using this package to publish the npm build. It mostly works, however, it appears that Webpack does not play nice with the published module. It is trying to load the UMD build by default which fails with an error message of failing to statically extract dependencies:

```
WARNING in ../../node_modules/@feathersjs/hooks/umd/utils.js 3:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../../node_modules/@feathersjs/hooks/umd/base.js
 @ ../../node_modules/@feathersjs/hooks/umd/index.js
 @ ./src/plugins/ImageColorConverter/ImageColorConverter.ts 55:14-42
 @ ./src/index.ts 6:28-88
```

For more information, see this issue: https://github.com/feathersjs/hooks/issues/98

The two options I can think of is:

- Find the right flag to add to `package.json` for Webpack to automatically use the ESM build (which it currently does not seem to do but would be nice since we'll get tree shaking and such)
- Have an option for a CommonJS instead of a UMD build output (if it exists I didn't find it in the docs)

**Comment by dsherret** [comment]
@daffl try out the latest version. It will output CommonJS by default with the ability to specify a UMD module by using the `scriptModule: "umd"` option.

> Find the right flag to add to package.json for Webpack to automatically use the ESM build (which it currently does not seem to do but would be nice since we'll get tree shaking and such)

I'm surprised Webpack can't figure this out yet from the package.json. I'm not sure what can be done here, but let me know if you know of any ideas.

**Comment by daffl** [comment]
Wonderful, that did it, thank you! I tried to dig a bit into why Webpack isn't going for the ESM build but didn't come up with anything useful. According to the docs and examples I saw, all the necessary `package.json` fields are there.
