### ISSUE TITLE
Exclude `dom` type definitions by default

### ISSUE THREAD

**Issue by ah-yu** [denoland/dnt#131]
In some cases, if your program is not running in a browser, you should exclude `dom` type definitions for type checking.

For example:

1. create `mod.ts`
```ts
// mod.ts
export async function foo(url: string) {
  return await fetch(url).then((r) => r.json);
}
```
2. build without shims and pass type checking
3. run `ts-node ./npm/src/mod.ts` then compile failed
```
TSError: ⨯ Unable to compile TypeScript:
npm/src/mod.ts:2:16 - error TS2304: Cannot find name 'fetch'.
```

**Comment by dsherret** [comment]
Oh... I didn't realize that TypeScript was including the lib files by default.

I started working on this, but fixing it seems like a decent amount of work so I'm going to resolve it on Monday.

**Comment by dsherret** [comment]
Now waiting on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60591
