### ISSUE TITLE
Add peer dependency option to mappings

### ISSUE THREAD

**Issue by sgwilym** [denoland/dnt#137]
I'm building quite a few libraries which rely on one another. I'd like to be able to specify if a mapping could be added to the resulting package.json's `peerDependencies` instead of `dependencies`:

```
mappings: {
  "https://deno.land/x/earthstar@v7.1.0/mod.ts": {
    name: "earthstar",
    version: "^7.1.0",
    peerDependency: true
  },
},
```

**Comment by harrysolovay** [comment]
+1 for this feature; this is critically important to libraries which depend on the types of other library, which are ultimately supplied by end developers. A common use case: projects which abstract over the TSC programatic API and allow the end user to specify compiler version.
