### ISSUE TITLE
Bug: `undici` shim breaks

### ISSUE THREAD

**Issue by andre4ik3** [denoland/dnt#153]
The `undici` shim fails to install.

**Steps to Reproduce:**
1. Build a file that uses `fetch` with the snippet in the README, plus `undici` shim.
2. Observe

**Expected Behavior:**
It builds.

**Actual Behavior:**
Won't build. Lots of errors about Node packages not being found.

**Workarounds:**
Via this custom shim, but it will put `@types/node` as a full dependency:
```ts
custom: [
  {
    typesPackage: { name: "@types/node", version: "17.0.24" },
    package: { name: "@types/node", version: "17.0.24" },
    globalNames: [],
  },
],
```

<hr />
<details>
<summary>System Details</summary>
<br />
<ul>
<li>MacBook Pro 2020 M1 (ARM64)</li>
<li>macOS Big Sur 11.6.5</li>
<li>Deno 1.20.4</li>
<li>v8 10.0.139.6</li>
<li>TypeScript 4.6.2</li>
<li><code>dnt</code> 0.23.0</li>
</ul>
</details>

**Comment by chronark** [comment]
Having the same issue even without the undici shim. 

```bash
[dnt] Building project...
[dnt] Type checking...
dist/src/nodejs.ts:9:19 - error TS2307: Cannot find module 'https' or its corresponding type declarations.

9 import https from "https";
                    ~~~~~~~
dist/src/nodejs.ts:10:18 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

10 import http from "http";
                    ~~~~~~

error: Uncaught (in promise) Error: Had 2 diagnostics.
      throw new Error(`Had ${diagnostics.length} diagnostics.`);
         ```
Adding it via `devDependencies` inside `build({ package: { devDepdendencies: { "@types/node": "latest"}}}) or via `customDev` shim doesn't work.

only a normal shim works, like andre4ik mentioned

**Comment by dsherret** [comment]
To fix these errors the same way you would with npm, by adding a `@types/node` dev dependency like so (tested and this works):

```ts
await build({
  entryPoints: ["./mod.ts"],
  outDir: "./npm",
  shims: {
    undici: true
  },
  package: {
     name: "your-package",
     version: Deno.args[0],
     description: "Your package.",
     license: "MIT",
     repository: {
     type: "git",
       url: "git+https://github.com/username/repo.git",
     },
     bugs: {
       url: "https://github.com/username/repo/issues",
     },
    devDependencies: {
      "@types/node": "16.11.26"
    }
   },
  },
});
```

That said, I'll change it to automatically include these when using the "undici" shim in the next version.
