### ISSUE TITLE
Bug: `.js` extensions are emitted for `outDir/src/*.ts` file import statements

### ISSUE THREAD

**Issue by andre4ik3** [denoland/dnt#154]
**Steps to Reproduce:**
1. Have a project with 2 TypeScript files. One declares a type, another a function with that type as an argument or return statement. (There are other use cases where it breaks, but this is the simplest)
2. Build it with the snippet in the README.
3. (After fixing #153 if applicable) observe the output of `npm/src`.

**Expected Behavior:**
It builds fine, and imports are done using `import { Thing } from "./Thing.ts";`

**Actual Behavior:**
It builds fine and runs fine (can be imported and will work), but the actual source code **and typings** won't be fine. They will be like this: `import { Thing } from "./Thing.js";` (note the .js and not .ts) and TypeScript will infer the type as `any`.

<hr />
<details>
<summary>System Details</summary>
<br />
<ul>
<li>MacBook Pro 2020 M1 (ARM64)</li>
<li>macOS Big Sur 11.6.5</li>
<li>Deno 1.20.4</li>
<li>v8 10.0.139.6</li>
<li>TypeScript 4.6.2</li>
<li><code>dnt</code> 0.23.0</li>
</ul>
</details>

**Comment by dsherret** [comment]
This is expected behaviour. I know it's weird, but TS doesn't rewrite specifiers so they need to be what they will be at runtime.

> It builds fine and runs fine (can be imported and will work), but the actual source code and typings won't be fine.

Did you actually find something that doesn't work and have an example? Sounds like it's working.

**Comment by andre4ik3** [comment]
Yup, my bad. Sorry, I had a `import { Thing1, type Thing2 } from "...";`, which broke it. This had totally nothing to do with it haha.
Fixed by doing two separate imports on my side: `import { Thing1 }` then `import type { Thing2 }`.
