### ISSUE TITLE
Ability to emit CJS only

### ISSUE THREAD

**Issue by roj1512** [denoland/dnt#187]

**Comment by roj1512** [comment]
Related lines:

https://github.com/denoland/dnt/blob/7446bd33e04618a3a3010ed0955bc8c505c84b9b/mod.ts#L312-L323

https://github.com/denoland/dnt/blob/7446bd33e04618a3a3010ed0955bc8c505c84b9b/lib/package_json.ts#L97

**Comment by roj1512** [comment]
@dsherret I was thinking about the way to modify the `BuildOptions` that is going to be good for you, that's why I opened this issue. If you don't have time, you can just tell me the implementation method of that option which you prefer, and I'll create the PR.

I was thinking about renaming `scriptModule` to `outputType` and changing its type to `string[]`, but liked to know your opinion.

**Comment by dsherret** [comment]
@roj1512 I think usually people will just disable either script or esm, so adding an `esmModule?: boolean` that defaults to true is sufficient. I think also having a `outputType: string[]` would get confusing when there can only be one kind of script module.

Thanks and sorry for my delay!

**Comment by roj1512** [comment]
@dsherret What if the user set `esModule` to `false` and `scriptModule` to `false`? Error?

**Comment by dsherret** [comment]
Yup
