### ISSUE TITLE
How to find packages authored using with dnt?

### ISSUE THREAD

**Issue by bebraw** [denoland/dnt#199]
This is more of a documentation/marketing question. From my perspective, it would be interesting to discover projects people have packaged using dnt as those can work as reference and maybe even help you with testing (i.e. testing a future version of the tool against existing projects to see if they still build the same etc.).

I wonder if it would make sense to write a `dnt` keyword to **package.json** `keywords` for example (probably opt-out?).

**Comment by dsherret** [comment]
Doing a search on cs.github.com for https://deno.land/x/dnt gives a list: https://cs.github.com/?scopeName=All+repos&scope=&q=https%3A%2F%2Fdeno.land%2Fx%2Fdnt
