### ISSUE TITLE
Comparison to deno2node

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/dnt#2]
There are already existing working solutions for this problem, I am mainly aware of [deno2node](https://github.com/wojpawlik/deno2node).

Can you explain if you have any objections regarding that project, and outline what advantages you're aiming for?

**Comment by dsherret** [comment]
The core difference is that this uses [deno_graph](https://github.com/denoland/deno_graph) to do the deno -> canonical typescript transform all in Rust. So someone could take that pipeline step and then send the output to a Typescript bundler if they wanted.

The deno.land/x/ module (https://deno.land/x/dnt) uses this transform to send the output to the typescript compiler and produce a compiled npm package that can be consumed from esm or cjs modules.

Overall, it's still very much a work in progress and I wouldn't recommend using it yet. I'd recommend deno2node.

**Comment by KnorpelSenf** [comment]
It looks like `dnt` has become the superior tool by now. There is one feature in `deno2node` that I'm missing before I can migrate. I opened #46 for it.
