### ISSUE TITLE
Published module does not work with react-scripts

### ISSUE THREAD

**Issue by waynebloss** [denoland/dnt#206]
Hello, I published [this module](https://github.com/waynebloss/sttyl) today to both [deno.land/x/sttyl](https://deno.land/x/sttyl@1.0.0) and then to [npm](https://www.npmjs.com/package/sttyl).

It's working great in Deno, but in my react-scripts (v3) project I get the following error when I try to import the NPM package:

```log
Failed to compile.

./node_modules/sttyl/esm/mod.js 56:19
Module parse failed: Unexpected token (56:19)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         arg = parseStyleCodes(arg);
|       } else {
>         arg = arg ?? "";
|       }
|
```

The line it's highlighting there is some es2020 code I think, with the coalesce operator in `arg = arg ?? "";`.

So, I'm wondering if there's a setting to make it target a lower es version?

Thanks!

**Comment by dsherret** [comment]
Hey, yeah try setting a lower `target` under `compilerOptions` in the build options (sorry am on my phone so too time consuming to show an example)

**Comment by waynebloss** [comment]
That works great! Thanks so much @dsherret
