### ISSUE TITLE
dnt without npm registry

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/dnt#208]
I know dnt is made to convert ts module(deno) to npm package but way why not make some trick to use deno tooling to develop and write js project to be runned with node (developper needs to have both deno and node in dev mode but only node in production) ? I'aim to see js-deno tools for node developer but without npm cli ( nor npm registry )

**Comment by kitsonk** [comment]
The Node.js ecosystem is tightly coupled to npm packages. The purpose of dnt is not to re-invent the Node.js ecosystem but make it easier for Deno code to participate in that ecosystem.

Packages created with dnt don't have to be uploaded to the public npm registry, they can be uploaded to private registries, but the format of packages are what Node.js uses.

Anything outside of this would be out of scope.
