### ISSUE TITLE
Is there a way to tree-shake dependencies?

### ISSUE THREAD

**Issue by JacobWeisenburger** [denoland/dnt#258]
I'm looking for a way to tree-shake dependencies such as `lodash`. 

I'm not really sure what other info you would need from me, so please let me know how I can help in getting this answered.

**Comment by dsherret** [comment]
No, that is out of scope. You can insert something that will alter the output in a post build step:

```ts
await build({
  // etc...
  postBuild() {
    // delete files or run some kind of tree shaker here
  }
});
```

That will be run before running the tests.
