### ISSUE TITLE
How to use node `fetch` from globalThis without undici package

### ISSUE THREAD

**Issue by MellKam** [denoland/dnt#259]
I would like to use a nodejs fetch api that can now be accessed globally, like in deno and browser, but I can't find an example of how to do this. Plus, I would also like to know how to use `URLSearchParams` and other global api that do not need to be shimed.

**Comment by MellKam** [comment]
I would also like to know how to use `URLSearchParams` and other global api.

**Comment by MellKam** [comment]
It seems like `compilerOptions.lib` with "dom" can handle this, so now i dont need to set typeCheck to `false`
```ts
compilerOptions: {
  lib: ["dom"],
},
```

**Comment by dsherret** [comment]
Yes, adding `lib: ["dom"]` is the way to do it.

> UPD: And I still can't run tests with this option.

Can you clarify what's not working? I just tried it out and it works for me.

**Comment by MellKam** [comment]
Thanks for the answer, I've already figured it out. The `lib: ["dom"]` works perfectly for me.
