### ISSUE TITLE
Support for `deno.json` `imports`

### ISSUE THREAD

**Issue by flevi29** [denoland/dnt#260]
Reproduction: https://github.com/flevi29/deno_import_map_test

Running `deno task build:npm` fails with `src/mod.ts:1:27 - error TS2307: Cannot find module 'fast-xml-parser' or its corresponding type declarations.`

**Comment by fro-profesional** [comment]
Same

**Comment by dsherret** [comment]
Sorry, it seems not documented, but you need to set the `importMap: "./deno.js"` option. I believe it should work.

**Comment by nhrones** [comment]
`set the importMap: "./deno.json" option` 
Set it where? VSCode settings?  cli command line?

**Comment by dsherret** [comment]
Sorry again. In the build options:

```
await build({
  ....
 "importMap": "deno.json",
});
```

**Comment by fro-profesional** [comment]
Thanks!
