### ISSUE TITLE
How to provide environment variables for tests?

### ISSUE THREAD

**Issue by MellKam** [denoland/dnt#273]
I'm wondering how I can provide env variables for nodejs tests? The only idea I have is to manually copy the .env file before the build to the output directory, but I would prefer to do it in some better way. For example, a preTest event in the build options or some property that will automatically pass the object as env variables. Or make a property that will remove the automatic launch of `npm test` and let it run manually with whatever environment variables I want

**Comment by dsherret** [comment]
You should be able to set any environment variables for the test in the post build hook, which runs after build and before the tests. These should then be inherited when it runs the node.js process for the tests:

```ts
await build({
  // ...
  postBuild() {
    // set your env variables here or load from the .env file (ex. https://deno.land/std@0.182.0/dotenv/mod.ts)
  },
});
```

**Comment by MellKam** [comment]
Oh, I hadn't noticed that preBuild was running before the tests. Thank you very much!
