### ISSUE TITLE
How do we override a tsconfig or specify my own

### ISSUE THREAD

**Issue by mcasaresmdevz** [denoland/dnt#284]
Hello,
I'm encountering an error while attempting to generate type declarations. The specific error message is:

```
error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
```
I believe I can resolve this issue by providing a tsconfig to DNT.

**Comment by dsherret** [comment]
What specific compiler option do you need? There are a subset of compiler options available on the `compilerOptions` property of the object provided to the `build` function.
