### ISSUE TITLE
[discussion] Better code using dnt causing lower quality ranking in npmjs.com

### ISSUE THREAD

**Issue by UrielCh** [denoland/dnt#298]
Hi,

I think npm [Package search rank criteria](https://docs.npmjs.com/searching-for-and-choosing-packages-to-download#package-search-rank-criteria) tend to lower the quality score of dnt project.

Since we do most of the heavy lifting on the deno side of the project, some Quality stuff is considered in npmjs criterion.

Would anyone happen to have any suggestions about that?

- I'm already sure that adding chalk@4 as a dependency is a bad thing since this is not the last version.
- I suspect that not having visible linting in the NPM version lower the project score.

----

good news chalk@4 will not be present using the last don't.

bad news the new dnt is not released yet.... please @dsherret publish the next version !!!

**Comment by dsherret** [comment]
Why would having chalk as a dev dependency affect npmjs ranking?

**Comment by UrielCh** [comment]
Having `chalk@latest` is not an issue, I think the npmjs' score is impacted by using not up-to-date dependency, so `chalk@4.X.X` was bad.

Project ranking is based on secret stuff.

The [official doc](https://docs.npmjs.com/searching-for-and-choosing-packages-to-download
) does not provide much information.

**Comment by UrielCh** [comment]
update:

I'm now peaty confident that using the old version of dev dependency decreases the Project Quality score.
1.0.2 quality score 51% (published 4 days ago)
1.0.3 quality score 90% (published just now) 
changes:
use picocolors@latest
use @types/node@latest

impressive.
