### ISSUE TITLE
Support mapping deno project source 

### ISSUE THREAD

**Issue by Gaubee** [denoland/dnt#310]
Currently source maps can only be source from `npm/src`.
I would like to be able to map to the source code of the deno project, which would be a great help for debugging.

**Comment by dsherret** [comment]
It would be nice, but unfortunately I believe it would be technically infeasible.

**Comment by Gaubee** [comment]
你是对的，这在技术上确实不可行。因此我找了一个折中的方法：
因为dnt的转换原理并不复杂，不会对源码做太多的改动，因此我直接将`npm/src`替换成我的源代码，它大部分情况下是能正常工作的：

```ts
/// before build
await Deno.remove("./electron/src").catch(() => {}); /// if is symlink, will be remove

await build({
  // ... build config
  postBuild() {
    Deno.removeSync("./electron/src", { recursive: true }); /// remove nodejs ts-source
    Deno.symlinkSync("./src", "./electron/src"); /// create symlink
  }
});
```
