### ISSUE TITLE
wasm file was always download from the network

### ISSUE THREAD

**Issue by Gaubee** [denoland/dnt#311]
if use `import { build } from "https://deno.land/x/dnt/mod.ts";`
the wasm file's url will be `https://deno.land/x/dnt/lib/pkg/dnt_wasm_bg.wasm`.

https://github.com/denoland/dnt/blob/main/lib/pkg/dnt_wasm.generated.js#L635
it will run `fetch(wasmUrl)`, without import from local:

for now I have to download the dnt source code and run it locally to avoid having to download wasm from the network every time I start up. This greatly improves startup efficiency. but I wish there was a better way.

**Comment by dsherret** [comment]
I need to land https://github.com/denoland/wasmbuild/pull/68
