### ISSUE TITLE
Is it possible to detect that a package was produced by dnt?

### ISSUE THREAD

**Issue by andrewbranch** [denoland/dnt#335]
I’m starting to add detected build tools to the metadata collected by https://arethetypeswrong.github.io. Most build tools can be detected by their presence in a package’s `devDependencies`, but dnt is different since it creates a fresh package.json and it’s not an npm package itself. Is there any way I can detect a package made with dnt from what’s present in the published package?

**Comment by dsherret** [comment]
I don't think there's any real easy way to tell. Maybe the precense of `@deno/shim-deno` in the deps or dev deps, but that might not be exactly correct.

Do you have a suggestion for something that could maybe be added to the package.json? That would obviously only help gradually in the future though.

**Comment by andrewbranch** [comment]
I don’t know of anything standard for that purpose, but I feel like the addition of a `"_generatedBy": "dnt@1.2.3"` field wouldn’t cause any problems.

**Comment by dsherret** [comment]
Seems to work in the latest release:

```
{
  "name": "code-block-writer",
  ...
  "_generatedBy": "dnt@0.39.0"
}
```

I have yet to publish anything with it, but from now on you should be able to tell if a package was published using dnt this way.
