### ISSUE TITLE
Please add `esnext.disposable` as an option in `build` > `compilerOptions` > `lib`

### ISSUE THREAD

**Issue by johnspurlock-skymethod** [denoland/dnt#345]
Currently this valid Deno interface causes `build` to fail in the type-checking step.

```ts
export interface Foo {
    [Symbol.dispose](): void;
}
```

It would be great to be able to specify `'esnext.disposable'` as an allowed value to the `lib` compiler option param to support this.

see: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html

**Comment by johnspurlock-skymethod** [comment]
Thanks!

**Comment by dsherret** [comment]
It's released now in 0.39.0. Just be aware that it doesn't polyfill `Symbol.dispose`, so you might have to add `(Symbol as any).dispose ??= Symbol("dispose")` (and similar for asyncDispose)

**Comment by johnspurlock-skymethod** [comment]
I had https://github.com/skymethod/kv-connect-kit/blob/becf1e22773a97030fa188ad371ebf4edbc91d7f/src/kv_types.ts#L2 in there for runtime, I think it's ok in my case since I only need Disposable.

Thanks again for the quick dnt release!  Was able to ignore the type issues with filterDiagnostic, but this will be much cleaner.
