### ISSUE TITLE
publish the next 0.39.1 ? or 0.40.0

### ISSUE THREAD

**Issue by UrielCh** [denoland/dnt#364]
Hi,

I'm stuck with one of my [project](https://deno.land/x/logger) that use Deno.stdout.isTerminal();

the isTerminal() is present in the latest @deno/shim-deno@0.18.0 but is not used by the latest dnt.

can [dsherret](https://github.com/denoland/dnt/commits?author=dsherret) publish the next verision ?

thx

**Comment by dsherret** [comment]
I'll publish it soon, but you can also just depend on the latest commit temporarily by importing https://raw.githubusercontent.com/denoland/dnt/6c00d71ab77f1454cd6cee3c59c8396b3ae12980/mod.ts

**Comment by dsherret** [comment]
By the way, I believe you can override the `@deno/shim-deno` dependency version used by specifying it under `packages` > `dependencies` in the build options

**Comment by dsherret** [comment]
Published https://github.com/denoland/dnt/releases/tag/0.40.0

**Comment by UrielCh** [comment]
I tried to override the @deno/shim-deno version using a custom import, but it failed on my first attempt. Then, I switched to something else.

dnt@0.40.0 fix the issue thx.
