### ISSUE TITLE
How to avoid rewriting `node:path` as `path`?

### ISSUE THREAD

**Issue by bebraw** [denoland/dnt#377]
I use imports like `import { join as joinPath } from "node:path";` in order to comply with the rules for Cloudflare Workers. In their environment, `node:` prefix is absolutely required.

It looks like dnt rewrites these imports without a prefix by default. Is there a way to change this behavior?

---

As an intermediate solution, it looks like rewriting the imports with [patch-package](https://www.npmjs.com/package/patch-package) works for now.

**Comment by dsherret** [comment]
That was done for Node < 18 support, but considering Node 16 is not end of life, I think it makes sense to remove this.
