### ISSUE TITLE
I would like to use `files` option in `package.json` instead of `.npmignore`

### ISSUE THREAD

**Issue by babakfp** [denoland/dnt#383]
I don't want the `.npmignore` file to be generated.

If the `files` option is specified, then don't do anything.

Currently, there is this warning:

```
Specifying `files` for the package.json is not recommended because it will cause the .npmignore file to not be respected.
```

**Comment by dsherret** [comment]
You can still use "files" if you'd like, but it's not recommended because dnt will usually manage that for you. You may just ignore the warning then delete the `.npmignore` file before publishing. Does that work?

**Comment by babakfp** [comment]
I moved back to using node.
Thanks.
