### ISSUE TITLE
Incorrect .npmignore generation

### ISSUE THREAD

**Issue by oscarotero** [denoland/dnt#387]
Coming from https://github.com/ventojs/vento/issues/48

dnt adds the `src/` folder to the `.npmignore` file, to don't include this folder in the package.
The problem is this matches also with `esm/src/` folder. It should include a slash at the begining (`/src/`, to make sure only the root src folder is ignored.
Probably all paths in this file should start with slash, to prevent other issues like that.

**Comment by dsherret** [comment]
I'll take a look into this now because I'm goign to do a release soon.
