### ISSUE TITLE
Is it mandatory to generate al typing files twice ?

### ISSUE THREAD

**Issue by UrielCh** [denoland/dnt#401]
Hi,

In my npm package containing ESM + CommonJS exports, I use to only generate my typing once in the ESM folder, then reference it juste once on .exports.[.].types and in .typings in my package.json.

can the ESM and CJS typing can be different, in some case ?

if not, why do dnt generate typing twice in the npm package ?

thx.

**Comment by dsherret** [comment]
You can use the `declaration: "separate"` option to generate only one set of types that are shared by the esm and cjs code, but then your package will fail on https://arethetypeswrong.github.io since the TypeScript team recommends generating a type declaration file per output.

**Comment by UrielCh** [comment]
Thx david, I will check that tomorrow.

**Comment by UrielCh** [comment]
https://arethetypeswrong.github.io/ looks greate but I can not add a custom tag or version...
