### ISSUE TITLE
JSR imports are failing in test files

### ISSUE THREAD

**Issue by vicary** [denoland/dnt#405]
I have a test file, let's call it `MyModule.test.ts`.

It is passing `deno test`, but the type checking in DNT fails to recognize the imports.

I am adding JSR imports via `deno add` and the entries are inside `deno.json`.

Here is the DNT output with errors.

```
[dnt] Transforming...
[dnt] Running npm install...

added 3 packages, and audited 4 packages in 571ms

found 0 vulnerabilities
[dnt] Building project...
[dnt] Type checking ESM...
src/MyModule.test.ts:1:30 - error TS2307: Cannot find module '@std/assert' or its corresponding type declarations.

1 import { assertThrows } from "@std/assert";
                               ~~~~~~~~~~~~~
src/MyModule.test.ts:2:30 - error TS2307: Cannot find module '@std/testing/bdd' or its corresponding type declarations.

2 import { describe, it } from "@std/testing/bdd";
                               ~~~~~~~~~~~~~~~~~~
src/MyModule.test.ts:3:52 - error TS2307: Cannot find module '@std/testing/mock' or its corresponding type declarations.

3 import { assertSpyCall, assertSpyCalls, spy } from "@std/testing/mock";
                                                     ~~~~~~~~~~~~~~~~~~~

error: Uncaught (in promise) Error: Had 3 diagnostics.
          throw new Error(`Had ${diagnostics.length} diagnostics.`);
                ^
    at getProgramAndMaybeTypeCheck (https://jsr.io/@deno/dnt/0.41.1/mod.ts:468:17)
    at build (https://jsr.io/@deno/dnt/0.41.1/mod.ts:354:17)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async file:///Users/vicary/my-module/dnt.ts:7:1
```

1. Should test files be ignored from type checks when the specified entrypoints and their import trees do not include them?
2. If they are meant to be included, how should I config DNT to resolve JSR imports?

**Comment by dsherret** [comment]
It's probably this. You need to provide it manually as an import map atm: https://github.com/denoland/dnt/issues/399

**Comment by vicary** [comment]
Thanks for the quick reply, adding `importMap: "./deno.json"` does build!

But the resulting package not includes all the testing dependencies that I really want to exclude from NPM, is it possible to skip the test files in DNT?

**Comment by dsherret** [comment]
> But the resulting package now includes all the testing dependencies that I really want to exclude from NPM, is it possible to skip the test files in DNT?

They should be marked as `"devDependencies"`. Can you open a separate issue that reproduces and shows the problem?
