### ISSUE TITLE
Exclude test files from the build

### ISSUE THREAD

**Issue by vicary** [denoland/dnt#406]
This is a continuation of https://github.com/denoland/dnt/issues/405#issuecomment-2105938878 by @dsherret for a more preferenced solution to the original issue.

# The issue

When publishing to NPM, I have a preference of removing all of the original sources and test files, leaving only these files:
1. bundled files
2. sourcemaps
3. package.json
4. LICENSE
5. README.md

In NPM this is achievable via the `files` properly in `package.json`, but it seems DNT always copy everything into the output directory.

## Possible solutions

1. Add `files` option to DNT. After running tests, DNT publishes only the files matched by `files` in the output directory.
6. Add a `postTest()` hook which is similar to `scripts.prepare`, `scripts.prepublishOnly` and the deprecated `scripts.prepublish` where users can remove unnecessary files before the actual publish happens.

## Current alternatives

1. Delete the test files before running `build()`. Cons: requires additional care to not commit these changes.
2. Delete the test files on `postBuild()`. Cons: skips tests after bundling.

**Comment by dsherret** [comment]
dnt should be ignoring all test files via the npmignore file. Can you include a reproduction if it's not?

For removing additional files, you can use a `postBuild` step to modify the output directory before publishing.

**Comment by vicary** [comment]
It turns out the generated .npmignore skips most of the files that I'd like to skip by default, although adding `src/` in the root `.npmignore` does not prevent DNT from copying it to `outDir`.

Using `postBuild` to remove the output `src/` does most of the things I wanted.

The default behavior for the generated .npmignore is desired, but undocumented, can I consider this a stable feature?

**Comment by dsherret** [comment]
Yes. It sounds like this issue can be closed?

**Comment by vicary** [comment]
Yes, and thanks a lot for the help!
