### ISSUE TITLE
use strict

### ISSUE THREAD

**Issue by mfulton26** [denoland/dnt#41]
So that code transformed from Deno to Node behaves consistently I suggest emitting `"use strict";` as part of the transformation.

See also https://github.com/denoland/deno/issues/12804.

**Comment by mfulton26** [comment]
💯 thank you!

**Comment by dsherret** [comment]
@mfulton26 thanks for reporting this! I didn't realize it wasn't emitting `"use strict";` (I copied a compiler option from deno's code that shouldn't have been copied)
