### ISSUE TITLE
Runtime-specific type definitions/files

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/dnt#46]
I have a library that consumes byte streams from the user. It supports different types per platform.

On Deno, we have
```ts
type SupportedByteStream =
  | string // file path
  | Deno.File
```
and on Node, we have
```ts
type SupportedByteStream =
  | string // file path
  | ReadStream
```
(This is simplified to illustrate the point, in fact we have eight (six) supported sources per platform.)

We are currently using `deno2node` which can rewrite import statements to use one file on Deno and another file on Node, so basically a strategy pattern on a module-basis.

Can we also have `dnt` support this? Note that it is not possible to branch at runtime the way it is described at https://github.com/denoland/dnt#node-and-deno-specific-code because the type signatures change at compile-time. Our generic code must handle both versions of `SupportedByteStream`, and we want it to be type-checked for both runtimes before shipping it.

If you don't want to add too much magic (such as the `.deno.ts`→`.node.ts` import rewrites), then one possible solution I could image would be to explicitly specify the two versions of the same file in the `mappings` config, or to support a new config option next to it. Something along the lines of
```json
{
  "./src/platform.deno.ts": "./src/platform.node.ts"
}
```
would be neat.

This missing feature is basically the last thing that prevents us from migrating.

**Comment by KnorpelSenf** [comment]
This is equivalent to supporting custom shim files.

**Comment by KnorpelSenf** [comment]
@dsherret what is your opinion on supporting this? I could imagine to look into implementing this if you agree that it's worth the effort.

**Comment by dsherret** [comment]
@KnorpelSenf I think it's something we should do. I'm just wondering how we could support it. I think probably it would be the automatic `*.deno.ts` and `*.node.ts`, but it would only pull these files if they were local (so it wouldn't work for remote modules).
