### ISSUE TITLE
dnt from npm to ts/js deno module

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/dnt#50]
thank you for this project
it seems node and deno will coexist for long time.
dnt will allow in some situation to write js universal library with ts-deno ecosystem but we need need think in other direction I mean convert npm package ( may be without deps ) to deno.land/x registry in a way we can convert any nodejs project to js code working on deno.
I know skypack convert npm modules to esm and deno std/node and deno compat try to solve this problem but I don't see any integration/mixing all those for global solution

**Comment by dsherret** [comment]
> dnt will allow in some situation to write js universal library with ts-deno ecosystem but we need need think in other direction I mean convert npm package ( may be without deps ) to deno.land/x registry in a way we can convert any nodejs project to js code working on deno.

We've thought about this and it's much harder to create a tool like dnt for going from node to deno. Probably esm.sh and skypack are the best bet.
