### ISSUE TITLE
TypeError at `Object.hasOwn`

### ISSUE THREAD

**Issue by kt3k** [denoland/dnt#51]
While transforming https://deno.land/std@0.112.0/flags/mod.ts, I saw the following type error:

```
npm/src/deps/deno_land/std_0.112.0/flags/mod.ts:66:9 - error TS2339: Property 'hasOwn' does not exist on type 'ObjectConstructor'.

66 const { hasOwn } = Object;
           ~~~~~~
```

~~I guess this is because the tsc used by dnt is a little older than what Deno uses.~~ (typescript looks at the latest version. ref: https://github.com/denoland/dnt/pull/44)

What would be the correct workaround (or fix) for this situation?

Note: I also saw a similar error about `err.cause`

Side note: I'm working on updating license_checker on this PR https://github.com/kt3k/deno_license_checker/pull/23

**Comment by dsherret** [comment]
I will investigate this now in #34.

Duplicates #34

**Comment by dsherret** [comment]
Should be fixed in the latest version.

**Comment by kt3k** [comment]
Thanks, David!
