### ISSUE TITLE
Support for import-map

### ISSUE THREAD

**Issue by grenierdev** [denoland/dnt#98]
I'm building a library of multiple packages under `/modules` folder, called [Baseless](https://github.com/baseless-dev/baseless). I've both configured an `importmap.json` while developing to redirect import to the local version. Everything works fine with the Deno CLI and with VSCode.

Is there a way to specify the path to my import map to `build`?

**Comment by grenierdev** [comment]
I've published my [experimental branch](https://github.com/baseless-dev/baseless/tree/universal-ts) that uses `dnt` to build all my modules. I've commented out [this line](https://github.com/baseless-dev/baseless/blob/709929b9e1732cdacea15c94c5e2baf332338d08/build.ts#L42) in my `build.ts` that build the module `provider-mail-sendgrid` but can't find modules that would otherwise be found with the import-map.

If I can help in any way, let me know!

**Comment by dsherret** [comment]
@grenierdev there is a new `importMap` property in 0.16:

https://github.com/denoland/dnt/blob/1c9b2c58559736427619bc433c9d42c814750a20/mod.ts#L89

Let me know if you run into any trouble.

**Comment by okikio** [comment]
@dsherret Can you please add this to the docs for dnt

**Comment by dsherret** [comment]
@okikio opened #178. For the future, I'd recommend opening new issues for action items. It's very easy for a comment to get lost in old closed/resolved issues or PRs.

**Comment by okikio** [comment]
Oh, ok
